/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LmsRouteImport } from './routes/lms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminLmsRouteImport } from './routes/admin.lms'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LmsRoute = LmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLmsRoute = AdminLmsRouteImport.update({
  id: '/admin/lms',
  path: '/admin/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/lms': typeof AdminLmsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/lms': typeof AdminLmsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/lms': typeof AdminLmsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/lms'
    | '/login'
    | '/admin/cms'
    | '/admin/lms'
    | '/clubs/$slug'
    | '/events/$slug'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/lms'
    | '/login'
    | '/admin/cms'
    | '/admin/lms'
    | '/clubs/$slug'
    | '/events/$slug'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/lms'
    | '/login'
    | '/admin/cms'
    | '/admin/lms'
    | '/clubs/$slug'
    | '/events/$slug'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LmsRoute: typeof LmsRoute
  LoginRoute: typeof LoginRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminLmsRoute: typeof AdminLmsRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lms': {
      id: '/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof LmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lms': {
      id: '/admin/lms'
      path: '/admin/lms'
      fullPath: '/admin/lms'
      preLoaderRoute: typeof AdminLmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LmsRoute: LmsRoute,
  LoginRoute: LoginRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminLmsRoute: AdminLmsRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
